### PR TITLE
Complete revised adapter core.

### PR DESCRIPTION
**Pull request by TGuybrush**
The received value are now identified by the Obis value instead of a fixed position in the UDP packet.
- Add frequency
- Removed dead code

The new revision makes the adapter more robust against future enhancements in the protocol and makes it easy adaptable.
Future changes planned:
- Code cleaning
- Improve connection status
- Fix update rate of timestamp and software version

### CODE REVIEW

**Comment by Apollon77** [comment]
Hey, ist there a Test fredbaxk from another user? I could not test it and also Not verify that the changes make sense beside „code wise“ ...

**Comment by TGuybrush** [comment]
I fixed the bug which occurs with the latest firmware of the SMA-EM device. That means I have it running for several weeks and I've checked all values so far. I don't have a feedback from other users since I don't know how it can be provided to make it easy accessible for other users?

**Comment by Apollon77** [comment]
You can start a Forum thread and Users can do aGithub install directly from your Github Fork ... is this an option?

**Comment by TGuybrush** [comment]
I've created a new issue #98 to invite other people to test the version.

**Comment by rolsch** [comment]
"The update just overwrites the normal sma-em adapter."
-> this was the solution :-)

Now i've tested the TGuybrush git.
After some hours, i think the modifyed code works well.
I see the frequency object and the other values are correct...
image

**Comment by rolsch** [comment]
Any news for the [#98](https://github.com/iobroker-community-adapters/ioBroker.sma-em/issues/98).

I've tested the changes and see no issues.

**Comment by Apollon77** [comment]
testing wise make sure that version in package.json and io-package is in sync

**Comment by TGuybrush** [comment]
Some guys have tested the new version. After a few updates everything looks good.
I ask for accepting of the pull request.

**Comment by DutchmanNL** [comment]
Nice job @TGuybrush thank you very much !
This adapter ist used by 360 + people but I know, also from past, that testing feedback is hard for this one to get.

Adapter is not yet stable, so I will merge this PR (looks very good and verified some stuff) and release ist as a beta to latest.
Let's have it in there for a month, if there are issue people can simply downgrade the version.

If we have no issue after that, its also time to release this one to stable !

I don't get the version bump to 0.6.1 (>Major<.>Minor<.>Patch<) so I will keep it on 0.6.0-beta.1 for the NPM package as its not a patch only and adding new functionality 👍

**Comment by DutchmanNL** [comment]
Update : Just noticed the perfectly updated readme..... agree 0.6.1 you made a patch thanks being that complete in your coding and documentation much appreciated !

**Pull request merged**
